server:
  port: 8080
spring:
  application:
    name: spring-fts
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/testdb
    username: sa
    password: 123123
    #    url: jdbc:mysql://localhost:3306/mikepro
    #    username: sa
    #    password: 123123
    hikari:
      auto-commit: false
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
task:
  execution:
    pool:
      schedule:
        max-size : 5
        allow-core-thread-timeout : true
        core-size : 10
        keep-alive : 60
        queue-capacity : 100
        name : 'mylove-'
